### ISSUE TITLE
Fix duplicate type

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/mongis-web#11]
![image](https://user-images.githubusercontent.com/30463117/176610543-a51c0bb7-0f72-4598-944e-9d64f14c0c45.png)

**Comment by russel0907** [comment]
Fix duplicate type word
![Screenshot (374)](https://user-images.githubusercontent.com/94702093/176618230-315b883c-7f91-4480-9d08-55eb71bc4d98.png)
