### ISSUE TITLE
Find suitable template

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/mongis-web#2]

**Comment by russel0907** [comment]
# Find suitable template 

## template 1
https://technext.github.io/arkitektur/

## template 2
https://technext.github.io/woody/

## template 3
https://technext.github.io/klift/index.html#

## template 4
https://technext.github.io/mosaic/index.html

## template 5
https://technext.github.io/woodrox/index.html

## template 6
https://html.design/preview/?theme=digitf

## template 7
https://html.design/preview/?theme=woodo

## template 8
https://html.design/preview/?theme=fiu

**Comment by rosclaritha** [comment]
Proceed to design the website with the following template: https://technext.github.io/woodrox/index.html
