### ISSUE TITLE
change `our commitment` design

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/mongis-web#29]
- [x] suggest a few designs and put designs in comment below:

![image](https://github.com/phisoft/mongis-web/assets/30463117/0fc5e320-18fe-4d50-a04f-099965393e56)

**Comment by raziqrakee** [comment]
Design 1:

**Comment by raziqrakee** [comment]
Design 1: 
Design 2:
Design 3:
Design 4:
Design 5:

**Comment by raziqrakee** [comment]
@rosclaritha 

Design 1: https://www.behance.net/gallery/107355971/Features-section-design/modules/615519471
<img width="1128" alt="Screenshot 2023-10-03 at 2 09 07 PM" src="https://github.com/phisoft/mongis-web/assets/97151754/aa3a3d81-7d7b-4f92-ba33-4a1f13e50784">

Design 2: https://www.behance.net/gallery/135985753/Features-Section-Design/modules/769343501
<img width="1440" alt="Screenshot 2023-10-03 at 2 10 22 PM" src="https://github.com/phisoft/mongis-web/assets/97151754/9010b6d4-57b9-4836-b443-8b6ad924319d">

Design 3: https://www.lendlease.com/au/sustainability/our-approach/
<img width="1440" alt="Screenshot 2023-10-03 at 2 14 54 PM" src="https://github.com/phisoft/mongis-web/assets/97151754/6e00b52b-7eb0-4f2f-815d-b4589175291d">

Design 4: https://uidoor.com/downloads/free-construction-website-design/
<img width="865" alt="Screenshot 2023-10-03 at 2 18 44 PM" src="https://github.com/phisoft/mongis-web/assets/97151754/26b969a2-f400-43b8-8b47-65623b108f24">

Design 5: https://www.free-css.com/free-css-templates/page294/woody
<img width="1278" alt="Screenshot 2023-10-03 at 2 23 13 PM" src="https://github.com/phisoft/mongis-web/assets/97151754/699c64b7-a482-46d9-ac5a-433e3deb2993">

Design 6: https://www.free-css.com/free-css-templates/page293/fonicy
<img width="1278" alt="Screenshot 2023-10-03 at 2 30 04 PM" src="https://github.com/phisoft/mongis-web/assets/97151754/fade9093-24f9-42aa-a12f-5dafd3aa5043">
