### ISSUE TITLE
Update website copywriting

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/mongis-web#5]
[Mongis Works Website Copywriting.pdf](https://github.com/phisoft/mongis-web/files/8938255/Mongis.Works.Website.Copywriting.pdf)

**Comment by russel0907** [comment]
Update website copywriting

## web update
![Screenshot 2022-06-20 at 16-59-43 Mongis](https://user-images.githubusercontent.com/94702093/174565499-44f211d2-fbf9-4c7a-9969-0005f13f7577.png)

**Comment by russel0907** [comment]
**Website contents' copywriting update progress**

1. Update contents' copywriting
2. adjust font-size to increase website's readability

## About 
![Screenshot 2022-06-21 at 15-13-13 Mongis](https://user-images.githubusercontent.com/94702093/174739550-ed55cb0c-8e3e-4bd4-97af-bc2c8b5500c1.png)

## Features
![Screenshot 2022-06-21 at 15-13-13 Mongis - Copy](https://user-images.githubusercontent.com/94702093/174739603-43ec197a-d2f4-4417-ab72-fc9619237e94.png)

## Work
![Screenshot 2022-06-21 at 15-13-13 Mongis - Copy - Copy](https://user-images.githubusercontent.com/94702093/174739639-c2c4d6bb-9056-4d8a-bc00-c8ead8c47bc7.png)

## Contact
![Screenshot 2022-06-21 at 15-13-13 Mongis - Copy - Copy - Copy](https://user-images.githubusercontent.com/94702093/174739688-248983a9-29bb-4582-a570-06d569c51835.png)
