### ISSUE TITLE
Update website logo 

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/mongis-web#9]
You can retrieve the latest logo from the following issue: https://github.com/phisoft/mongis-web/issues/8

**Comment by russel0907** [comment]
Update website logo 

## tab
![Screenshot (372)](https://user-images.githubusercontent.com/94702093/176074401-4a14dc84-9b09-4223-b9f2-931316d7d936.png)


## webs
![Mongis (1)](https://user-images.githubusercontent.com/94702093/176074491-885a0582-cbec-4abf-8ec5-a51f3ef80a29.png)
![Mongis (2)](https://user-images.githubusercontent.com/94702093/176075125-3c599bbd-ab6c-4b32-aa8f-a9727c41a755.png)
